version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - /home/dantoine/data/wordpress:/var/www/html
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - ./.env
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - /home/dantoine/data/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - DOMAIN_NAME=${WP_URL}
    env_file:
      - ./.env
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - /home/dantoine/data/mariadb:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dantoine/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dantoine/data/wordpress
